Repository RedPRL/sml-redprl, pull requests merged in 2018-02, with the labels that each got.

#588 Semi-Simplicial Types: First Contact
  example/semi-simplicial.prl
  src/redprl/redprl.grm
  src/redprl/refiner.fun
  src/redprl/refiner.sig
  src/redprl/refiner_types.fun
  src/redprl/syntax/operator.sig
  src/redprl/syntax/operator.sml
  src/redprl/tactic_elaborator.fun
Labels: A-example

#597 Printing of universes.
  emacs/redprl.el
  src/redprl/machine.fun
  src/redprl/pretty.sml
  src/redprl/redprl.grm
  src/redprl/redprl.lex
  src/redprl/refiner_types.fun
  src/redprl/syntax/kind.sml
  test/success/equality.prl
  vim/syntax/redprl.vim
Labels: A-parser, A-printer

#598 Put the aux goals due to synth almost at the end. Close #595.
  example/semi-simplicial.prl
  example/tutorial.prl
  src/redprl/refiner_types.fun
Labels: A-rules

#599 Profiling should use the same parameters as for building.
  script/profile.sh
Labels: A-build

#608 Fix EqElim.
  src/redprl/refiner_kit.fun
  src/redprl/refiner_types.fun
Labels: A-rules

#604 Ultimate rewrite with multiple accessors.
  example/omega1s1.prl
  example/semi-simplicial.prl
  src/redprl/redprl.grm
  src/redprl/refiner.fun
  src/redprl/refiner.sig
  src/redprl/refiner_types.fun
  src/redprl/syntax/operator.sig
  src/redprl/syntax/operator.sml
  src/redprl/tactic_elaborator.fun
  test/success/num.prl
Labels: A-rules

#606 Fix branchOnDim on meta variables. Close #605.
  src/redprl/machine.fun
  test/success/V-types.prl
Labels: A-computation-system

#607 Implement V.EqProj and kill autoSynthesizableNeu.
  src/redprl/list_util.sml
  src/redprl/refiner.fun
  src/redprl/refiner_types.fun
Labels: A-rules

#614 Goodbye, weak bools. We will not miss you.
  emacs/redprl.el
  example/README.prl
  example/tutorial.prl
  src/redprl/machine.fun
  src/redprl/redprl.grm
  src/redprl/redprl.lex
  src/redprl/refiner.fun
  src/redprl/refiner_types.fun
  src/redprl/syntax/operator.sig
  src/redprl/syntax/operator.sml
  src/redprl/syntax/view.sml
  test/success/S1-fcom.prl
  test/success/S1.prl
  test/success/wbool-fhcom.prl
  vim/syntax/redprl.vim
Labels: A-computation-system, A-example, A-parser, A-rules, E-easy, I-cleanup

#596 Add comments to example/semi-simplicial.prl
  example/semi-simplicial.prl
Labels: A-documentation, A-example

#611 Fix the error message for failing non-det search.
  src/redprl/refiner.fun
Labels: A-frontend

#616 Starting our documentation!
  .gitignore
  doc/Makefile
  doc/old/machine.tex
  doc/src/conf.py
  doc/src/index.rst
  doc/src/overview.rst
  doc/src/static/uphold-cubical-thought.jpg
Labels: A-documentation

#620 Write documentation.
  .travis.yml
  doc/src/atomic-judgment.rst
  doc/src/conf.py
  doc/src/index.rst
  doc/src/language.rst
  doc/src/overview.rst
  doc/src/refine.rst
  doc/src/static/red.css
  doc/src/tutorial.rst
  script/test-sphinx.sh
Labels: A-documentation

#629 Computation of J.
  example/J.prl
Labels: A-example

#632 Make int a normal inductive type. Solve #628.
  doc/src/refine.rst
  emacs/redprl.el
  example/omega1s1.prl
  example/univalence.prl
  src/redprl/error.sig
  src/redprl/error.sml
  src/redprl/machine.fun
  src/redprl/redprl.grm
  src/redprl/redprl.lex
  src/redprl/refiner.fun
  src/redprl/refiner_types.fun
  src/redprl/syntax/operator.sig
  src/redprl/syntax/operator.sml
  src/redprl/syntax/view.sml
  test/success/num.prl
  vim/syntax/redprl.vim
Labels: A-documentation, A-elaborator, A-rules, E-easy
